import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs Neo4j</title>
        <meta name="description" content="Generated by Nouz" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Hello Sir!</div>
      </main>
    </>
  );
}
